- name: Installer Cordova
        run: npm install -g cordova

      - name: Corriger le nom du dossier
        run: '[ -d ww ] && [ ! -d www ] && mv ww www || true'

      - name: Ajouter la plateforme Android
        run: cordova platform add android